<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLAPZvas\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLAPZvas/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLAPZvas.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLAPZvas\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLAPZvas\App_KernelDevDebugContainer([
    'container.build_hash' => 'LAPZvas',
    'container.build_id' => '7b23a53f',
    'container.build_time' => 1767816941,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLAPZvas');
