<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMnKu0a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMnKu0a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMnKu0a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMnKu0a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMnKu0a\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMnKu0a',
    'container.build_id' => 'dfb68f39',
    'container.build_time' => 1767883413,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMnKu0a');
